General:
    comment: 
    seed: 4090
    fp16: True
    amp_level: O2
    precision: 16
    multi_gpu_mode: dp
    gpus: [1]
    epochs: &epoch 1
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: True
    data_dir: Camelyon16/pt_files/
    label_dir: dataset_csv/camelyon16/
    fold: 0
    nfold: 4

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 2


Optimizer:
    opt: lookahead_radam
    lr: 0.0001
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.0000045

Loss:
    base_loss: CrossEntropyLoss

